spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
# Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
logging:
  level:
    sun.rmi: OFF
